development:
  adapter: mysql2
  encoding: utf8
  database: depot-development
  pool: 5
  host: localhost
  username: root
  password: root

test:
  adapter: mysql2
  encoding: utf8
  database: depot-test
  pool: 5
  username: root
  password: root
